#!/usr/bin/env python3
"""Check the early boot marker against the memory it writes to.

    ci/check-boot-marker.py

The marker is a handful of instructions at the top of primary_entry that write a ramoops-formatted
record across the pstore reservation, before the MMU, any console or any driver exists. After a failed
boot and a power cycle, Gemian's pstore exposes it: marker present means our kernel ran, marker absent
means LK never jumped. That one bit is the difference between debugging the kernel and debugging the
boot image, and nothing else we have can tell them apart.

Because it writes to physical memory with the MMU off, getting the address wrong corrupts whatever
lives there instead. So the constants in head.S are checked against the reservation in our own dtsi,
and the signature against the vendor kernel that has to read it back.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HEAD_S = REPO / "arch/arm64/kernel/head.S"
# The reservation moved to the board file when the SoC file became an include of mt8183.dtsi, so look
# in both rather than pinning one path.
C_MARK = REPO / "arch/arm64/kernel/cosmo-mark.c"
SETUP_C = REPO / "arch/arm64/kernel/setup.c"
RAM_C = REPO / "fs/pstore/ram.c"
PLATFORM_C = REPO / "fs/pstore/platform.c"
C_SOURCES = "".join(f.read_text() for f in (C_MARK, SETUP_C, RAM_C, PLATFORM_C) if f.exists())
DT_FILES = (REPO / "arch/arm64/boot/dts/mediatek/mt6771-planet-cosmo.dts",
            REPO / "arch/arm64/boot/dts/mediatek/mt6771.dtsi")
# fs/pstore/ram_core.c:46 in the vendor kernel: #define PERSISTENT_RAM_SIG (0x43474244) /* DBGC */
PERSISTENT_RAM_SIG = 0x43474244


def movz_movk(src: str, reg: str) -> int | None:
    """Reconstruct the constant a movz/movk pair builds into `reg`."""
    val, seen = 0, False
    for m in re.finditer(rf"\b(movz|movk)\s+[wx]{reg},\s*#(0x[0-9a-fA-F]+)(?:,\s*lsl\s*#(\d+))?", src):
        seen = True
        val |= int(m.group(2), 16) << int(m.group(3) or 0)
    return val if seen else None


def main() -> int:
    if not HEAD_S.exists():
        print(f"missing {HEAD_S}")
        return 1
    src = HEAD_S.read_text()
    if "cosmo_mark" not in src:
        print("head.S carries no boot marker")
        return 1

    # Every stage must write the same region, so one bad constant cannot send one stage somewhere else.
    stages = re.findall(r"cosmo_mark\s+0x([0-9a-f]{4})\s*//\s*stage\s*(\d+)", src)
    c_stages = re.findall(r'cosmo_mark\("COSMO-MARK-(\d+)"\)', C_SOURCES)
    # stages generated by the COSMO_MARK_STAGE macro rather than written out
    c_stages += re.findall(r'COSMO_MARK_STAGE\(\w+,\s*(\d+)\)', C_SOURCES)
    tags = [f"stage {n} (asm)" for _, n in stages] + [f"stage {n} (C)" for n in c_stages]
    print("marker stages found: " + ", ".join(tags) if tags else "no stages found")
    if not stages:
        print("no asm marker stages")
        return 1
    asm_nums = sorted(int(n) for _, n in stages)
    all_nums = sorted(asm_nums + [int(n) for n in c_stages])
    if all_nums != list(range(1, len(all_nums) + 1)):
        print(f"stages are not consecutive from 1: {all_nums}")
        return 1
    tails = {tail for tail, _ in stages}
    if len(tails) != len(stages):
        print("two asm stages write the same tag; they cannot be told apart")
        return 1

    # Every tag is memcpy'd at exactly COSMO_MARK_LEN (12) bytes, so a longer one is silently truncated.
    # COSMO-PROBE-I and COSMO-PROBE-O both became "COSMO-PROBE-" and could not be told apart, which cost
    # an attempt. Tags must be exactly 12 characters and distinct.
    all_tags = re.findall(r'cosmo_mark\("([^"]+)"\)', C_SOURCES)
    all_tags += [f"COSMO-MARK-{n}" for n in re.findall(r'COSMO_MARK_STAGE\(\w+,\s*(\d+)\)', C_SOURCES)]
    bad = [tag for tag in all_tags if len(tag) != 12]
    if bad:
        for tag in bad:
            print(f"tag {tag!r} is {len(tag)} characters; it is copied at 12 and would be truncated")
        return 1
    if len(set(all_tags)) != len(all_tags):
        dupes = sorted({tag for tag in all_tags if all_tags.count(tag) > 1})
        print(f"duplicate tags, which cannot be told apart: {dupes}")
        return 1
    print(f"tags: {', '.join(sorted(set(all_tags)))}")

    block = src[src.index(".macro\tcosmo_mark"):][:1600]
    start, end, sig = movz_movk(block, "5"), movz_movk(block, "6"), movz_movk(block, "7")
    if None in (start, end, sig):
        print(f"could not read the marker constants: start={start} end={end} sig={sig}")
        return 1

    # The reservation the marker writes into, from our own device tree.
    m = None
    for f in DT_FILES:
        if not f.exists():
            continue
        m = re.search(r"ramoops@[0-9a-f]+\s*\{[^}]*?reg\s*=\s*<\s*0\s+(0x[0-9a-f]+)\s+0\s+(0x[0-9a-f]+)",
                      f.read_text(), re.S)
        if m:
            print(f"reservation read from {f.name}")
            break
    if not m:
        print("no ramoops reg found in " + " or ".join(f.name for f in DT_FILES))
        return 1
    base, size = int(m.group(1), 16), int(m.group(2), 16)

    print(f"marker writes 0x{start:08x}..0x{end:08x}, reservation 0x{base:08x}..0x{base + size:08x}")
    ok = True
    if sig != PERSISTENT_RAM_SIG:
        print(f"signature 0x{sig:08x} != PERSISTENT_RAM_SIG 0x{PERSISTENT_RAM_SIG:08x}; pstore will not find it")
        ok = False
    if start < base:
        print(f"marker starts 0x{base - start:x} bytes before the reservation")
        ok = False
    if end > base + size:
        print(f"marker runs 0x{end - (base + size):x} bytes past the reservation — it would corrupt memory we do not own")
        ok = False
    if start >= end:
        print("marker range is empty")
        ok = False
    if C_MARK.exists():
        cbase = re.search(r"COSMO_MARK_BASE\s+0x([0-9a-fA-F]+)", C_MARK.read_text())
        cend = re.search(r"COSMO_MARK_END\s+0x([0-9a-fA-F]+)", C_MARK.read_text())
        if not (cbase and cend):
            print("cosmo-mark.c does not define the region")
            ok = False
        elif (int(cbase.group(1), 16), int(cend.group(1), 16)) != (start, end):
            print(f"cosmo-mark.c writes 0x{int(cbase.group(1), 16):08x}..0x{int(cend.group(1), 16):08x} "
                  f"but head.S writes 0x{start:08x}..0x{end:08x}; the stages would not overwrite each "
                  "other and the furthest-reached tag would be meaningless")
            ok = False
    print("boot marker: ok" if ok else "boot marker: FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
