#!/usr/bin/env python3
"""Check the early boot marker against the memory it writes to.

    ci/check-boot-marker.py

The marker is a handful of instructions at the top of primary_entry that write a ramoops-formatted
record across the pstore reservation, before the MMU, any console or any driver exists. After a failed
boot and a power cycle, Gemian's pstore exposes it: marker present means our kernel ran, marker absent
means LK never jumped. That one bit is the difference between debugging the kernel and debugging the
boot image, and nothing else we have can tell them apart.

Because it writes to physical memory with the MMU off, getting the address wrong corrupts whatever
lives there instead. So the constants in head.S are checked against the reservation in our own dtsi,
and the signature against the vendor kernel that has to read it back.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HEAD_S = REPO / "arch/arm64/kernel/head.S"
# The reservation moved to the board file when the SoC file became an include of mt8183.dtsi, so look
# in both rather than pinning one path.
C_MARK = REPO / "arch/arm64/kernel/cosmo-mark.c"
SETUP_C = REPO / "arch/arm64/kernel/setup.c"
RAM_C = REPO / "fs/pstore/ram.c"
PLATFORM_C = REPO / "fs/pstore/platform.c"
C_SOURCES = "".join(f.read_text() for f in (C_MARK, SETUP_C, RAM_C, PLATFORM_C) if f.exists())
DT_FILES = (REPO / "arch/arm64/boot/dts/mediatek/mt6771-planet-cosmo.dts",
            REPO / "arch/arm64/boot/dts/mediatek/mt6771.dtsi")
# fs/pstore/ram_core.c:46 in the vendor kernel: #define PERSISTENT_RAM_SIG (0x43474244) /* DBGC */
PERSISTENT_RAM_SIG = 0x43474244


def movz_movk(src: str, reg: str) -> int | None:
    """Reconstruct the constant a movz/movk pair builds into `reg`."""
    val, seen = 0, False
    for m in re.finditer(rf"\b(movz|movk)\s+[wx]{reg},\s*#(0x[0-9a-fA-F]+)(?:,\s*lsl\s*#(\d+))?", src):
        seen = True
        val |= int(m.group(2), 16) << int(m.group(3) or 0)
    return val if seen else None


def main() -> int:
    if not HEAD_S.exists():
        print(f"missing {HEAD_S}")
        return 1
    src = HEAD_S.read_text()
    if "cosmo_mark" not in src:
        print("head.S carries no boot marker")
        return 1

    # Every stage must write the same region, so one bad constant cannot send one stage somewhere else.
    stages = re.findall(r"cosmo_mark\s+0x([0-9a-f]{4})\s*//\s*stage\s*(\d+)", src)
    c_stages = re.findall(r'cosmo_mark\("COSMO-MARK-(\d+)"\)', C_SOURCES)
    # stages generated by the COSMO_MARK_STAGE macro rather than written out
    c_stages += re.findall(r'COSMO_MARK_STAGE\(\w+,\s*(\d+)\)', C_SOURCES)
    tags = [f"stage {n} (asm)" for _, n in stages] + [f"stage {n} (C)" for n in c_stages]
    print("marker stages found: " + ", ".join(tags) if tags else "no stages found")
    if not stages:
        print("no asm marker stages")
        return 1
    asm_nums = sorted(int(n) for _, n in stages)
    all_nums = sorted(asm_nums + [int(n) for n in c_stages])
    if all_nums != list(range(1, len(all_nums) + 1)):
        print(f"stages are not consecutive from 1: {all_nums}")
        return 1
    tails = {tail for tail, _ in stages}
    if len(tails) != len(stages):
        print("two asm stages write the same tag; they cannot be told apart")
        return 1

    # Every tag is memcpy'd at exactly COSMO_MARK_LEN (12) bytes, so a longer one is silently truncated.
    # COSMO-PROBE-I and COSMO-PROBE-O both became "COSMO-PROBE-" and could not be told apart, which cost
    # an attempt. Tags must be exactly 12 characters and distinct.
    all_tags = re.findall(r'cosmo_mark\("([^"]+)"\)', C_SOURCES)
    all_tags += [f"COSMO-MARK-{n}" for n in re.findall(r'COSMO_MARK_STAGE\(\w+,\s*(\d+)\)', C_SOURCES)]
    bad = [tag for tag in all_tags if len(tag) != 12]
    if bad:
        for tag in bad:
            print(f"tag {tag!r} is {len(tag)} characters; it is copied at 12 and would be truncated")
        return 1
    if len(set(all_tags)) != len(all_tags):
        dupes = sorted({tag for tag in all_tags if all_tags.count(tag) > 1})
        print(f"duplicate tags, which cannot be told apart: {dupes}")
        return 1
    print(f"tags: {', '.join(sorted(set(all_tags)))}")

    # Once ramoops claims the region (cosmo_mark_claimed = true in ramoops_probe, before any zone is
    # initialised) every marker must land on the single tag page inside the pmsg zone and nowhere else:
    # the console zone then holds the real log, and the tag page tells how far the console writes got.
    # Sprays after the claim erased four logs; the kill switch that replaced them hid the second write.
    if RAM_C.exists():
        ram = RAM_C.read_text()
        claim = ram.find("cosmo_mark_claimed = true;")
        first_zone = ram.find('ramoops_init_przs("dmesg"')
        if claim == -1 or first_zone == -1 or claim > first_zone:
            print("fs/pstore/ram.c: ramoops_probe must set cosmo_mark_claimed = true before it initialises "
                  "the first zone, or a later marker can spray over the console log")
            return 1
    if PLATFORM_C.exists():
        plat = PLATFORM_C.read_text()
        w = plat.find("static void pstore_console_write(")
        w_end = plat.find("\n}\n", w)
        body = plat[w:w_end]
        first_write = body.find("psinfo->write(&record);")
        if w == -1 or first_write == -1:
            print("fs/pstore/platform.c: pstore_console_write not found")
            return 1
        if "cosmo_mark(" in body or "cosmo_mark_len(" in body or "cosmo_mark_off" in body:
            print("fs/pstore/platform.c: pstore_console_write may only use cosmo_note_pw(); a stage tag or "
                  "a kill switch there hides the console writes it should count")
            return 1
        ent, ok = body.find("cosmo_note_pw(false, c);"), body.find("cosmo_note_pw(true, c);")
        if not (0 <= ent < first_write < ok):
            print("fs/pstore/platform.c: cosmo_note_pw(false) must precede and cosmo_note_pw(true) must "
                  "follow psinfo->write in pstore_console_write, so the tag page counts entries and returns")
            return 1
    if "cosmo_mark_off" in C_SOURCES:
        print("cosmo_mark_off is retired: after the claim, markers go to the tag page instead of going quiet")
        return 1

    block = src[src.index(".macro\tcosmo_mark"):][:1600]
    start, end, sig = movz_movk(block, "5"), movz_movk(block, "6"), movz_movk(block, "7")
    if None in (start, end, sig):
        print(f"could not read the marker constants: start={start} end={end} sig={sig}")
        return 1

    # The reservation the marker writes into, from our own device tree.
    m = None
    for f in DT_FILES:
        if not f.exists():
            continue
        m = re.search(r"ramoops@[0-9a-f]+\s*\{[^}]*?reg\s*=\s*<\s*0\s+(0x[0-9a-f]+)\s+0\s+(0x[0-9a-f]+)",
                      f.read_text(), re.S)
        if m:
            print(f"reservation read from {f.name}")
            break
    if not m:
        print("no ramoops reg found in " + " or ".join(f.name for f in DT_FILES))
        return 1
    base, size = int(m.group(1), 16), int(m.group(2), 16)

    print(f"marker writes 0x{start:08x}..0x{end:08x}, reservation 0x{base:08x}..0x{base + size:08x}")
    ok = True
    if sig != PERSISTENT_RAM_SIG:
        print(f"signature 0x{sig:08x} != PERSISTENT_RAM_SIG 0x{PERSISTENT_RAM_SIG:08x}; pstore will not find it")
        ok = False
    if start < base:
        print(f"marker starts 0x{base - start:x} bytes before the reservation")
        ok = False
    if end > base + size:
        print(f"marker runs 0x{end - (base + size):x} bytes past the reservation — it would corrupt memory we do not own")
        ok = False
    if start >= end:
        print("marker range is empty")
        ok = False
    if C_MARK.exists():
        cm_src = C_MARK.read_text()
        cbase = re.search(r"COSMO_MARK_BASE\s+0x([0-9a-fA-F]+)", cm_src)
        cend = re.search(r"COSMO_MARK_END\s+0x([0-9a-fA-F]+)", cm_src)
        if not (cbase and cend):
            print("cosmo-mark.c does not define the region")
            ok = False
        else:
            # head.S may only write the pmsg zone (the last pmsg-size bytes of the reservation): its
            # MMU-off stores came back on top of ramoops' console records after every reset.
            pm2 = re.search(r"pmsg-size\s*=\s*<\s*(0x[0-9a-f]+)\s*>", DT_FILES[0].read_text())
            c_end = int(cend.group(1), 16)
            if not pm2 or (start, end) != (c_end - int(pm2.group(1), 16), c_end):
                print(f"head.S writes 0x{start:08x}..0x{end:08x}; it may only write the pmsg zone "
                      f"(the last pmsg-size bytes ending at 0x{c_end:08x}), never the console zone")
                ok = False
        # C must never write the reservation through the cacheable linear map except on the tag page:
        # such writes came back after a reset on top of ramoops' own write-combined records.
        if "COSMO_MARK_STRIDE" in cm_src or "cosmo_spray" in cm_src:
            print("cosmo-mark.c still sprays the reservation from C; only head.S (MMU off) may do that")
            ok = False
        # the tag page (twice: line and header) and the console-zone header, nothing else
        if cm_src.count("phys_to_virt(") > 4:
            print("cosmo-mark.c maps more than the tag page and the console-zone header")
            ok = False
    if C_MARK.exists():
        cm = C_MARK.read_text()
        page = re.search(r"COSMO_TAG_PAGE\s+0x([0-9a-fA-F]+)", cm)
        pm = re.search(r"pmsg-size\s*=\s*<\s*(0x[0-9a-f]+)\s*>", DT_FILES[0].read_text())
        if not (page and pm):
            print("no COSMO_TAG_PAGE in cosmo-mark.c or no pmsg-size in the dts")
            ok = False
        else:
            tag_page, pmsg = int(page.group(1), 16), int(pm.group(1), 16)
            pmsg_start = base + size - pmsg
            if tag_page != pmsg_start:
                print(f"COSMO_TAG_PAGE 0x{tag_page:08x} is not the start of the pmsg zone 0x{pmsg_start:08x}; "
                      "the vendor kernel reads exactly that page back as pmsg-ramoops-0")
                ok = False
            else:
                print(f"tag page 0x{tag_page:08x} = start of the pmsg zone")
            cz = re.search(r"COSMO_CONSOLE_ZONE\s+0x([0-9a-fA-F]+)", cm)
            cs = re.search(r"console-size\s*=\s*<\s*(0x[0-9a-f]+)\s*>", DT_FILES[0].read_text())
            if cz and cs and int(cz.group(1), 16) != pmsg_start - int(cs.group(1), 16):
                print(f"COSMO_CONSOLE_ZONE 0x{int(cz.group(1), 16):08x} is not the console zone header "
                      f"0x{pmsg_start - int(cs.group(1), 16):08x}")
                ok = False
    print("boot marker: ok" if ok else "boot marker: FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
